export const SET_BOOK = 'SET_BOOK'
export const SET_IS_READY = 'SET_IS_READY'
export const ADD_BOOK_TO_CART = 'ADD_BOOK_TO_CART'
export const REMOVE_BOOK_FROM_CART = 'REMOVE_BOOK_FROM_CART'
export const SET_FILTER = 'SET_FILTER'